@token = {{login.response.body.token}}

### Test Register User
POST http://localhost:5001/api/users/register
Content-Type: application/json

{
    "email": "jiannaclarisse.tm@gmail.com",
    "name": "Lola Tessie",
    "password": "SinigangNaBaboy",
    "familyCode": "TALA2026",
    "birthdate": "1969-05-04T12:00:00Z",
    "bloodType": "B+",
    "allergies": ["Peanuts"],
    "medicalConditions": [],
    "maintenanceMeds": [],
    "currentStreak": 0,
    "lastLogDate": "2026-05-04T12:00:00Z"
}

### Test Register User
POST http://localhost:5001/api/users/register
Content-Type: application/json

{
    "email": "dobadoba911@gmail.com",
    "name": "Papa",
    "password": "SinigangNaBaboy",
    "familyCode": "TALA2026",
    "role": "Manager",
    "birthdate": "1989-05-04T12:00:00Z",
    "bloodType": "B+",
    "allergies": ["Peanuts"],
    "medicalConditions": ["Diabetes"],
    "maintenanceMeds": [
        {
            "name": "Metformin", 
            "days": ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
            "time": []
        }
    ],
    "currentStreak": 0,
    "lastLogDate": "2026-05-04T12:00:00Z"
}


### Test Login User
# @name login
POST http://localhost:5001/api/users/login
Content-Type: application/json

{
    "email": "dobadoba911@gmail.com",
    "password": "SinigangNaBaboy"
}

### Test Get Family Members
GET http://localhost:5001/api/users/member/69fa0a3a382914c64efbdbbb
Authorization: Bearer {{token}}

### Test Get Family Members
GET http://localhost:5001/api/users/family/TALA2026
Authorization: Bearer {{token}}

### Test Update Info
PUT http://localhost:5001/api/users/profile/edit-info/69fa0a3a382914c64efbdbbb
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Lola Tessie"
}

### Create a Lab Test
POST http://localhost:5001/api/lab-tests/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "familyCode": "TALA2026",
    "member": "69fa0a3f382914c64efbdbbc",
    "testName": "Blood Sugar Level",
    "testDate": "2026-05-06T08:00:00Z",
    "notes": "Fast for 8 hours before test.",
    "attachments": ["https://cloudinary.com/result123.pdf"]
}

### Get Member Tests
GET http://localhost:5001/api/lab-tests/member/TALA2026/69fa0a3f382914c64efbdbbc
Authorization: Bearer {{token}}

### Get Family Tests
GET http://localhost:5001/api/lab-tests/family/TALA2026
Authorization: Bearer {{token}}


# ========= SYSTEM ROUTES ===========
### Test Notify Member
POST http://localhost:5001/api/system/notify-member
x-system-key: your_super_secret_key_here
Content-Type: application/json

{
    "familyCode": "TALA2026",
    "member": "69fa0a3f382914c64efbdbbc",
    "message": "Testing"
}

### Test Notify Family
POST  http://localhost:5001/api/system/notify-family
x-system-key: your_super_secret_key_here
Content-Type: application/json

{
  "familyCode": "TALA2026",
  "message": "Time for Lola's 10 PM medicine!"
}

### Test Remove Notification
DELETE  http://localhost:5001/api/system/delete/69fa19354c422e9db73c6bd1
Authorization: Bearer {{token}}



