@token = {{login.response.body.token}}

### Test Register User
POST http://localhost:5001/api/users/register
Content-Type: application/json

{
    "name": "Lola Tessie",
    "password": "SinigangNaBaboy",
    "familyCode": "TALA2026",
    "birthdate": "1969-05-04T12:00:00Z",
    "bloodType": "B+",
    "allergies": ["Peanuts"],
    "medicalConditions": [],
    "maintenanceMeds": [],
    "currentStreak": 0,
    "lastLogDate": "2026-05-04T12:00:00Z"
}

### Test Register User
POST http://localhost:5001/api/users/register
Content-Type: application/json

{
    "name": "Papa",
    "password": "SinigangNaBaboy",
    "familyCode": "TALA2026",
    "role": "Manager",
    "birthdate": "1989-05-04T12:00:00Z",
    "bloodType": "B+",
    "allergies": ["Peanuts"],
    "medicalConditions": ["Diabetes"],
    "maintenanceMeds": [
        {
            "name": "Metformin", 
            "days": ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
            "time": []
        }
    ],
    "currentStreak": 0,
    "lastLogDate": "2026-05-04T12:00:00Z"
}


### Test Login User
# @name login
POST http://localhost:5001/api/users/login
Content-Type: application/json

{
    "name": "Lola Tessie",
    "password": "SinigangNaBaboy",
    "familyCode": "TALA2026"
}

### Test Get Family Members
GET http://localhost:5001/api/users/family/TALA2026

### Test Update Info
PUT http://localhost:5001/api/users/profile/edit-info/69f9c807249de3db4766d276
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Lola Tessie"
}

### Test Notify Member
POST http://localhost:5001/api/notifications/notify-member
x-system-key: your_super_secret_key_here
Content-Type: application/json

{
    "familyCode": "TALA2026",
    "member": "69f9c807249de3db4766d276",
    "message": "Testing"
}

### Test Notify Family
POST  http://localhost:5001/api/notifications/notify-family
x-system-key: your_super_secret_key_here
Content-Type: application/json

{
  "familyCode": "TALA2026",
  "message": "Time for Lola's 10 PM medicine!"
}

### Test Remove Notification
DELETE  http://localhost:5001/api/notifications/delete/69f9faa419c41dc3acb83d8c
Authorization: Bearer {{token}}
